using System;
using System.Drawing;
using System.Windows.Forms;
using TLShoes.Common;
using TLShoes.ViewModels;

namespace TLShoes.FormControls.KeHoachSanXuat
{
    public partial class ucKeHoachSanXuatList : BaseForm
    {
        public ucKeHoachSanXuatList()
        {
            InitializeComponent();

            ObserverControl.Regist(Define.ActionType.SAVE, this.Name, ReloadData);
            ObserverControl.Regist(Define.ActionType.REFRESH, this.Name, ReloadData);


            GenerateFormatRuleByValue(bandedGridView1, colLoaiNguoiDung, Define.LoaiNguoiDung.GDSX.ToString(), Color.Wheat, Color.Red);
            GenerateFormatRuleByValue(bandedGridView1, colLoaiNguoiDung, Define.LoaiNguoiDung.CBDH.ToString(), Color.Honeydew, Color.Green);
            GenerateFormatRuleByValue(bandedGridView1, colLoaiNguoiDung, Define.LoaiNguoiDung.PVT.ToString(), Color.Honeydew, Color.Green);
            GenerateFormatRuleByValue(bandedGridView1, colLoaiNguoiDung, Define.LoaiNguoiDung.PKT.ToString(), Color.Honeydew, Color.Green);
            GenerateFormatRuleByValue(bandedGridView1, colLoaiNguoiDung, Define.LoaiNguoiDung.TRUONG_PKT.ToString(), Color.Honeydew, Color.Green);
            GenerateFormatRuleByValue(bandedGridView1, colLoaiNguoiDung, Define.LoaiNguoiDung.TRUONG_PVT.ToString(), Color.Honeydew, Color.Green);
            GenerateFormatRuleByValue(bandedGridView1, colLoaiNguoiDung, Define.LoaiNguoiDung.GDSX.ToString(), Color.Honeydew, Color.Green);
            // This line of code is generated by Data Source Configuration Wizard
            this.keHoachSanXuatInstantFeedbackSource.GetQueryable += entityInstantFeedbackSource1_GetQueryable;
            // This line of code is generated by Data Source Configuration Wizard
            this.keHoachSanXuatInstantFeedbackSource.DismissQueryable += entityInstantFeedbackSource1_DismissQueryable;
        }

        public override void ReloadData()
        {
            gridControl.DataSource = null;
            gridControl.DataSource = keHoachSanXuatInstantFeedbackSource;
        }

        private void gridView_DoubleClick(object sender, EventArgs e)
        {
            ThreadHelper.LoadForm(() =>
            {
                var info = SF.Get<KeHoachSanXuatViewModel>().GetDetail(GetFocusRowId(sender));
                if (info != null)
                {
                    FormFactory<Main>.Get().ShowPopupInfo(info);
                }
            });
        }

        // This event is generated by Data Source Configuration Wizard
        void entityInstantFeedbackSource1_GetQueryable(object sender, DevExpress.Data.Linq.GetQueryableEventArgs e)
        {

            // Instantiate a new DataContext
            TLShoes.GiayTLEntities dataContext = new TLShoes.GiayTLEntities();
            // Assign a queryable source to the EntityInstantFeedbackSource
            e.QueryableSource = dataContext.KeHoachSanXuats;
            // Assign the DataContext to the Tag property,
            // to dispose of it in the DismissQueryable event handler
            e.Tag = dataContext;
        }

        // This event is generated by Data Source Configuration Wizard
        void entityInstantFeedbackSource1_DismissQueryable(object sender, DevExpress.Data.Linq.GetQueryableEventArgs e)
        {

            // Dispose of the DataContext
            ((TLShoes.GiayTLEntities)e.Tag).Dispose();
        }

        private void bandedGridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            LoadImageAsyncGrid(sender, e, "Hinh", "DonHang.HinhAnh");
        }
    }
}
