//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoPhanXuong
    {
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActived { get; set; }
        public Nullable<long> DonHangId { get; set; }
        public string PhanXuong { get; set; }
        public int SanLuongKhoan { get; set; }
        public int SanLuongThucHien { get; set; }
        public System.DateTime BaoCaoNgay { get; set; }
        public string GhiChu { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
