//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXuatKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietXuatKho()
        {
            this.NhatKyXuatKhoes = new HashSet<NhatKyXuatKho>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActived { get; set; }
        public Nullable<long> PhieuXuatKhoId { get; set; }
        public Nullable<long> NguyenLieuId { get; set; }
        public float SoLuong { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual PhieuXuatKho PhieuXuatKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhatKyXuatKho> NhatKyXuatKhoes { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
