//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThongSo
    {
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public Nullable<long> BangThongSoId { get; set; }
        public Nullable<long> ChiTietId { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<double> ThongSo { get; set; }
    
        public virtual BangThongSo BangThongSo { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
