//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongNgheSanXuat
    {
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public Nullable<long> DonHangId { get; set; }
        public Nullable<long> MauDoiId { get; set; }
        public Nullable<long> PhanLoaiThuRapId { get; set; }
        public string YKienThuRap { get; set; }
        public Nullable<long> PhanLoaiThuDao { get; set; }
        public string YKienThuDao { get; set; }
        public string HinhBangThongSo { get; set; }
        public Nullable<long> NgayDuyet { get; set; }
        public string HinhCongNgheDuocDuyet { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual MauDoi MauDoi { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual DanhMuc DanhMuc1 { get; set; }
    }
}
