//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActived { get; set; }
        public Nullable<long> ToTrinhId { get; set; }
        public string SoDH { get; set; }
        public Nullable<long> NhaCungCapId { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public System.DateTime NgayGiaoHang { get; set; }
        public int DungYeuCauKyThuat { get; set; }
        public int DungThoiGian { get; set; }
        public int DungMau { get; set; }
        public int DatTestLy { get; set; }
        public int DatTestHoa { get; set; }
        public int Gia { get; set; }
        public int DichVuGiaoHang { get; set; }
        public int DichVuHauMai { get; set; }
        public int Khac { get; set; }
        public System.DateTime NgayDuyet { get; set; }
        public Nullable<long> NguoiDuyetId { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<long> NguoiLapId { get; set; }
        public string TrangThai { get; set; }
        public float SoLuongDat { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual UserAccount UserAccount1 { get; set; }
        public virtual UserAccount UserAccount2 { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhaCungCap NhaCungCap1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
    }
}
