//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public Nullable<long> NhaCungCapId { get; set; }
        public Nullable<long> NgayDatHang { get; set; }
        public Nullable<long> NgayGiaoHang { get; set; }
        public string SoDH { get; set; }
        public Nullable<int> DungYeuCauKyThuat { get; set; }
        public Nullable<int> DungThoiGian { get; set; }
        public Nullable<int> DungMau { get; set; }
        public Nullable<int> DatTestLy { get; set; }
        public Nullable<int> DatTestHoa { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> DichVuGiaoHang { get; set; }
        public Nullable<int> DichVuHauMai { get; set; }
        public Nullable<int> Khac { get; set; }
        public Nullable<long> ToTrinhId { get; set; }
        public Nullable<long> NgayDuyet { get; set; }
        public Nullable<long> NguoiDuyetId { get; set; }
        public Nullable<long> NgayLap { get; set; }
        public Nullable<long> NguoiLapId { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual UserAccount NguoiDuyet { get; set; }
        public virtual UserAccount NguoiLap { get; set; }
        public virtual ToTrinh ToTrinh { get; set; }
    }
}
