//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.BaoCaoPhanXuongs = new HashSet<BaoCaoPhanXuong>();
            this.ChiLenhs = new HashSet<ChiLenh>();
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.CongNgheSanXuats = new HashSet<CongNgheSanXuat>();
            this.KeHoachSanXuats = new HashSet<KeHoachSanXuat>();
            this.MauDois = new HashSet<MauDoi>();
            this.ChiTietToTrinhs = new HashSet<ChiTietToTrinh>();
            this.MauSanXuats = new HashSet<MauSanXuat>();
            this.MauTests = new HashSet<MauTest>();
            this.MauThuDaos = new HashSet<MauThuDao>();
            this.HuongDanDongGois = new HashSet<HuongDanDongGoi>();
            this.PhieuXuatKhoes = new HashSet<PhieuXuatKho>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public string MaHang { get; set; }
        public Nullable<long> KhachHangId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<long> NgayNhan { get; set; }
        public Nullable<long> NgayXuat { get; set; }
        public string HinhAnh { get; set; }
        public string GopYVatTu { get; set; }
        public string GopYXuongChat { get; set; }
        public string GopYXuongMay { get; set; }
        public string GopYXuongDe { get; set; }
        public string GopYXuongGo { get; set; }
        public string GopYQc { get; set; }
        public string GopYCongNghe { get; set; }
        public string GopYMau { get; set; }
        public string GopYKhoVatTu { get; set; }
        public string GopYPhuTro { get; set; }
        public string GopYKhoThanhPham { get; set; }
        public Nullable<long> MaPhomId { get; set; }
        public Nullable<int> DungYeuCauKyThuat { get; set; }
        public Nullable<int> DungThoiGian { get; set; }
        public Nullable<int> DungMau { get; set; }
        public Nullable<int> DatTestLy { get; set; }
        public Nullable<int> DatTestHoa { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> DichVuGiaoHang { get; set; }
        public Nullable<int> DichVuHauMai { get; set; }
        public Nullable<int> Khac { get; set; }
        public Nullable<long> MuId { get; set; }
        public Nullable<long> LotId { get; set; }
        public Nullable<long> DaLotTayId { get; set; }
        public Nullable<long> DeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoCaoPhanXuong> BaoCaoPhanXuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiLenh> ChiLenhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongNgheSanXuat> CongNgheSanXuats { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeHoachSanXuat> KeHoachSanXuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauDoi> MauDois { get; set; }
        public virtual NguyenLieu Phom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietToTrinh> ChiTietToTrinhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauSanXuat> MauSanXuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauTest> MauTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauThuDao> MauThuDaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuongDanDongGoi> HuongDanDongGois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatKho> PhieuXuatKhoes { get; set; }
        public virtual NguyenLieu DaLotTay { get; set; }
        public virtual NguyenLieu De { get; set; }
        public virtual NguyenLieu Lot { get; set; }
        public virtual NguyenLieu Mu { get; set; }
    }
}
