//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeHoachSanXuat
    {
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public Nullable<long> DonHangId { get; set; }
        public Nullable<long> NgayKiemHang { get; set; }
        public Nullable<long> NgayBatDauPxChat { get; set; }
        public Nullable<long> NgayHoanThanhPxChat { get; set; }
        public Nullable<long> NgayBatDauToPhuTro { get; set; }
        public Nullable<long> NgayHoanThanhToPhuTro { get; set; }
        public Nullable<long> NgayBatDauPxMay { get; set; }
        public Nullable<long> NgayHoanThanhPxMay { get; set; }
        public Nullable<long> NgayBatDauPxGo { get; set; }
        public Nullable<long> NgayHoanThanhPxGo { get; set; }
        public Nullable<long> NgayBatDauPxDe { get; set; }
        public Nullable<long> NgayHoanThanhPxDe { get; set; }
        public Nullable<long> NgayBatDauBpVatTu { get; set; }
        public Nullable<long> NgayHoanThanhBpVatTu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
