//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
            this.MauHuongDanDongGois = new HashSet<MauHuongDanDongGoi>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public string TenCongTy { get; set; }
        public string TenNguoiDaiDien { get; set; }
        public string DiaChi { get; set; }
        public string Dienthoai { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string MatHang { get; set; }
        public Nullable<int> DungYeuCauKyThuat { get; set; }
        public Nullable<int> DungThoiGian { get; set; }
        public Nullable<int> DungMau { get; set; }
        public Nullable<int> DatTestHoa { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> DichVuGiaoHang { get; set; }
        public Nullable<int> DichVuHauMai { get; set; }
        public Nullable<int> Khac { get; set; }
        public string GhiChu { get; set; }
        public string GhiChuNoiBo { get; set; }
        public Nullable<int> DatTestLy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauHuongDanDongGoi> MauHuongDanDongGois { get; set; }
    }
}
