//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class MauTest
    {
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActived { get; set; }
        public Nullable<long> DonHangId { get; set; }
        public System.DateTime NgayGuiMau { get; set; }
        public System.DateTime NgayKetquaTestLy { get; set; }
        public string KetQuaTestLy { get; set; }
        public Nullable<long> PhanLoaiTestLyId { get; set; }
        public System.DateTime NgayKetquaTestHoa { get; set; }
        public string KetQuaTestHoa { get; set; }
        public Nullable<long> PhanLoaiTestHoaId { get; set; }
        public string GopYCongNghe { get; set; }
        public string GopYMau { get; set; }
        public string GopYQc { get; set; }
        public string GopYKhoVatTu { get; set; }
        public string GopYVatTu { get; set; }
        public string GopYPhuTro { get; set; }
        public string GopYXuongChat { get; set; }
        public string GopYXuongMay { get; set; }
        public string GopYXuongDe { get; set; }
        public string GopYXuongGo { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual DanhMuc DanhMuc1 { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
