//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using TLShoes.Common;

namespace TLShoes
{
    using System;
    using System.Collections.Generic;

    public partial class NhaCungCapVatTu
    {
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public Nullable<long> NhaCungCapId { get; set; }
        public Nullable<long> NguyenLieuId { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string DonVi { get; set; }
        public Nullable<long> GiaBanTuNgay { get; set; }
        public Nullable<long> GiaBanDenNgay { get; set; }

        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual UserAccount UserAccount { get; set; }

        public string GiaBanTuNgayFormat
        {
            get
            {
                var data = 0L;
                if (GiaBanTuNgay != null)
                {
                    data = (long)GiaBanTuNgay;
                }
                return TimeHelper.TimestampToString(data, "d");
            }
            set { GiaBanTuNgay = TimeHelper.StringToTimeStamp(value); }
        }

        public string GiaBanDenNgayFormat
        {
            get
            {
                var data = 0L;
                if (GiaBanDenNgay != null)
                {
                    data = (long)GiaBanDenNgay;
                }
                return TimeHelper.TimestampToString(data, "d");
            }
            set { GiaBanDenNgay = TimeHelper.StringToTimeStamp(value); }
        }
    }
}
