//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhapKho()
        {
            this.ChiTietNhapKhoes = new HashSet<ChiTietNhapKho>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public Nullable<long> CreatedDate { get; set; }
        public Nullable<long> ModifiedDate { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public string NguoiGiao { get; set; }
        public string DiaChi { get; set; }
        public string LyDo { get; set; }
        public string Kho { get; set; }
        public Nullable<long> NgayNhap { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<long> DanhGiaId { get; set; }
        public string TrangThai { get; set; }
        public Nullable<long> NgayDuyet { get; set; }
        public Nullable<long> NguoiDuyetId { get; set; }
        public Nullable<long> NgayLap { get; set; }
        public Nullable<long> NguoiLapId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhapKho> ChiTietNhapKhoes { get; set; }
        public virtual UserAccount UserAccount { get; set; }
        public virtual DanhGia DanhGia { get; set; }
        public virtual UserAccount NguoiDuyet { get; set; }
        public virtual UserAccount NguoiLap { get; set; }
    }
}
