//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLShoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToTrinh()
        {
            this.ChiTietToTrinhs = new HashSet<ChiTietToTrinh>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AuthorId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActived { get; set; }
        public Nullable<long> TongHopToTrinhId { get; set; }
        public Nullable<long> NguyenLieuId { get; set; }
        public float BoSung { get; set; }
        public float ThuHoi { get; set; }
        public float TonToTrinh { get; set; }
        public float TonTheKho { get; set; }
        public float TonThucTe { get; set; }
        public float DuKien { get; set; }
        public float HaoHut { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietToTrinh> ChiTietToTrinhs { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual TongHopToTrinh TongHopToTrinh { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
